export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';

export const SET_TAGS = 'SET_TAGS';
export const ADD_TAG = 'ADD_TAG';
export const UPDATE_TAG = 'UPDATE_TAG';
export const DELETE_TAG = 'DELETE_TAG';

export const SET_CATEGORY_GROUPS = 'SET_CATEGORY_GROUPS';
export const ADD_CATEGORY_GROUP = 'ADD_CATEGORY_GROUP';
export const UPDATE_CATEGORY_GROUP = 'UPDATE_CATEGORY_GROUP';
export const DELETE_CATEGORY_GROUP = 'DELETE_CATEGORY_GROUP';

export const SET_RECURRING    = 'SET_RECURRING';
export const ADD_RECURRING    = 'ADD_RECURRING';
export const UPDATE_RECURRING = 'UPDATE_RECURRING';
export const DELETE_RECURRING = 'DELETE_RECURRING';

export const SET_ACTIVE_MONTH = 'SET_ACTIVE_MONTH';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
